services:
  env:
    image: epitechcontent/epitest-docker:latest
    volumes:
      - .:/mnt/delivery
    working_dir: /mnt/delivery
    stdin_open: true
    tty: true
    command: bash

  lint:
    image: ghcr.io/super-linter/super-linter:slim-v6
    environment:
      - RUN_LOCAL=true
      - VALIDATE_ALL_CODEBASE=true
      - DEFAULT_BRANCH=main
    volumes:
      - .:/tmp/lint
